### PR TITLE
ManageCodesActivity

### PR DESCRIPTION
**Pull request by jJadsit**
It gets the users codes, and clicking on them directs to a ViewQRCodeActivity which currently has placeholder values.

### CODE REVIEW

**Comment by jJadsit** [comment]
I just pushed to my branch, so now this pull request will also include Unit Test changes.
There are several more unit tests now.

**Review by Gigantorz — COMMENTED** [review]
I apologize if its just my laptop, but does ManageCodesActivity run for you? And also do all the Test fail for you too or is it just for me?

**Review by Gigantorz — APPROVED** [review]
but like if the issues in my previous comments were normal, and all this pull request need was to be checked if it runs in my computer or not, then it does run.

**Comment by jJadsit** [comment]
None of the test cases will build and I'm not sure whats up with that. It gives weird errors I don't understand. I was hoping it was just on my end, but I guess thats not the case
ManageCodesActivity runs for me fine on my end, though.

**Comment by jJadsit** [comment]
I have changed up the code and the tests should work now.

**Comment by Gigantorz** [comment]
Ok I will look into it

**Comment by Gigantorz** [comment]
After deleting previously stored cache, you can now launch ManageCodesActivity

**Pull request merged**
